### ISSUE TITLE
Usage with Chrome Extension?

### ISSUE THREAD

**Issue by f0rr0** [hughfenghen/opfs-tools#14]
Is this intended / tested for Chrome Extensions?

Chrome extension has OPFS support through offscreen document.

Check Option 3 in this comment: https://github.com/w3c/webextensions/issues/352#issuecomment-1432900555

**Comment by hughfenghen** [comment]
The initial purpose of opfs-tools was to facilitate file operations in the main thread or a WebWorker. 
I haven't tried running it in an offscreen document.

**Comment by f0rr0** [comment]
Thanks, I will try it out! Closing the thread.

**Comment by hughfenghen** [comment]
Looking forward to your test results ~
