### ISSUE TITLE
DataCloneError in Safari/WebKit

### ISSUE THREAD

**Issue by xollaborator** [hughfenghen/opfs-tools#3]
![image](https://github.com/hughfenghen/opfs-tools/assets/54781638/353eab89-4534-4000-b7b8-170e13c6b956)

Unfortunately, this library doesn't work with WebKit. Maybe current implementation will work once this old bug is fixed but it is already years old: [https://bugs.webkit.org/show_bug.cgi?id=215485](https://bugs.webkit.org/show_bug.cgi?id=215485)

In our investigation with @czarsbenemoriendi we found that the root cause is in creation of FileHandle in main thread and then using postMessage to pass it to worker which WebKit cannot serialize. We checked a simple fix and moved FileHandle creation to worker and that was enough to solved the issue. But of course it has impact on the performance in the benchmark that is part of this repo. 

We do not want to decide how to approach the issue according to the vision of opfs-tools but the rough solution might be verified here: https://github.com/Dev-Familia/opfs-tools/commit/599f65ff9ab9477bbbab927c858a896bad0af840

Would be nice to know what solution will be pursed for this issue. Let us know if we could help here more. Thanks.

**Comment by hughfenghen** [comment]
opfs-tools will strive to be compatible with Safari.

> We checked a simple fix and moved FileHandle creation to worker and that was enough to solved the issue. But of course it has impact on the performance in the benchmark that is part of this repo.

This is the correct solution. In most cases, the 'register' operation is not executed frequently, so it should not have a significant impact on performance.
![image](https://github.com/hughfenghen/opfs-tools/assets/3307051/db1515d7-a10d-4fa1-9e50-e06502f6e231)

**Comment by hughfenghen** [comment]
Fixed in v0.3.2

**Comment by xollaborator** [comment]
@hughfenghen thanks, I can confirm this solution is working in Safari. However, the sourcemap for worker is triggering a console issue in Safari (screenshot below) and Firefox is not able to find it. This is only a minor discomfort during local development and from my perspective sourcemaps might be not generated. 

![image](https://github.com/hughfenghen/opfs-tools/assets/54781638/1256278b-cb15-41ab-866c-a06e5070af60)

Since the main problem is solved I would normally close the issue but I leave it to you to decide in case you would like to ask me to verify something. 

Have a great day :)

**Comment by hughfenghen** [comment]
https://github.com/vitejs/vite/pull/5417

>One tricky edge case is the scenario where non-inline sourcemaps are being used with inline workers. In this case, the embedded comment has to use the full path (basepath + fileName) instead of simply using the file name. The tests don't address this case, partly because querying the inlined worker code would be pretty messy and it is something where manually running the playground catches the issue pretty easily.

Indeed, it is a tricky problem and I don't have a good way to solve it. The SourceMap file for the Worker is located here.
![image](https://github.com/hughfenghen/opfs-tools/assets/3307051/ead914c9-2b5b-46f0-b055-f1bfcfe52060)
