### ISSUE TITLE
反馈：write方法会报错Other writer have not been closed

### ISSUE THREAD

**Issue by caohongzhi1** [hughfenghen/opfs-tools#5]
报错信息如图，我是在调用一次write后又write了另一个文件，就报错了。
![image](https://github.com/hughfenghen/opfs-tools/assets/48698806/af83cb44-e48c-48c8-815b-d695cd095a2f)

**Comment by hughfenghen** [comment]
一个文件不能有两个 writer 同时存在，设计如此，避免覆盖内容

**Comment by caohongzhi1** [comment]
> 一个文件不能有两个 writer 同时存在，设计如此，避免覆盖内容

通过try catch处理了错误后不会影响后续操作，主要是怀疑文件写入操作后没有及时的释放，通过测试没有发现多次调用write的情况。

**Comment by hughfenghen** [comment]
应该是多次调用了 `createWriter` 且没有释放。

如果能复现，请提供一个最简化的项目。

**Comment by caohongzhi1** [comment]
确认了是因为多次调用write方法的问题，还在下载过程中就再次调用了，并且这种情况避免不了，最终通过添加了一个正在写入的列表，检测到在写入就重复检测到写入结束，感觉这个库没什么办法解决这个问题，有遇到这种情况的小伙伴可以参考我的方式。
