### ISSUE TITLE
opfs-tools 如何在chrome下强制持久化保存文件？

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/opfs-tools#6]
看文章提到是浏览器自动判断，但判断false就无法主动持久化保存文件了。需要如何实现？

**Comment by hughfenghen** [comment]
重新看一遍文章或官方文档，有说明。

**Comment by xeoshow** [comment]
看到过下面说明文档：
https://web.dev/articles/persistent-storage?hl=zh-cn#request_persistent_storage

但提到如下。这样无法设置方式强行设置为自己需要的选项？
```
Chrome 和其他基于 Chromium 的浏览器
Chrome 以及大多数其他基于 Chromium 的浏览器会自动处理权限请求，并且不会向用户显示任何提示。相反，如果网站被视为重要，系统会自动授予永久性存储权限，否则，系统会以静默方式拒绝该权限。
```

**Comment by xeoshow** [comment]
我本机现在就是返回false，就无法进一步设置了...

**Comment by hughfenghen** [comment]
> 浏览器会自动处理权限请求

浏览器自动处理也是有规则的，文章中有说明
