### ISSUE TITLE
Enhancement: Expose `OPFSDirWrap` and `OPFSFileWrap` types

### ISSUE THREAD

**Issue by ElasticBottle** [hughfenghen/opfs-tools#8]
Hello,
谢谢你写的library。
我在密码里使用`OPFSDirWrap` 和`OPFSFileWrap` 的 types。
因为它们没有被exported, 我是这样用：
```
export type DirectoryType = ReturnType<typeof dir>;
export type FileType = ReturnType<typeof file>;
```

跟next.js SSR 用的時候就会有一下的错误：
![image](https://github.com/hughfenghen/opfs-tools/assets/44563205/11eab9a0-f534-48e9-b8c9-f61ca01642e2)。

我先抱歉一下，写的华文有一點怪，我的华文沒那么好。

**Comment by hughfenghen** [comment]
type `FileSystemDirectoryHandle` is declared in `lib.dom.d.ts`, try adding "DOM" to the `lib` field in your project's tsconfig.json.

<img width="456" alt="image" src="https://github.com/hughfenghen/opfs-tools/assets/3307051/8de8fdd0-a5d5-4216-a001-a89df3fd37da">

Note: The OPFS API (including `FileSystemDirectoryHandle`) is not available in the Node.js.

_You can use English directly; I can understand the general meaning. ：）_

**Comment by ElasticBottle** [comment]
Will try this.

I believe I have `dom` as the target. It's just that `FileSystemDirectoryHandle` is being accessed during import of `file`/`dir` leading to the server side rendering error.

Will double  check and report back

**Comment by hughfenghen** [comment]
Try v0.5.4, which fixes the error thrown when importing 'opfs-tools' in Node.js.

https://github.com/hughfenghen/opfs-tools/commit/b44d501f4415e2e075a702ff555c90ece3e8b523

**Comment by ElasticBottle** [comment]
👍🏼 
Seems to be working. Getting a `navigator` undefined now during server side rendering though:
![image](https://github.com/hughfenghen/opfs-tools/assets/44563205/d3ee34ba-83c8-49d8-8a95-a91031e36d53)

**Comment by ElasticBottle** [comment]
Also, as an aside, any plans to expose the `OPFSDirWrap` and `OPFSFileWrap` types directly?

**Comment by hughfenghen** [comment]
> Seems to be working. Getting a navigator undefined now during server side rendering though:

In the Node.js context (SSR), OPFS-related APIs cannot be called. `opfs-tools` can only prevent errors from being thrown during import.

> Also, as an aside, any plans to expose the types directly?

```
export type DirectoryType = ReturnType<typeof dir>;
export type FileType = ReturnType<typeof file>;
```
This is a great approach. For now, `opfs-tools` will not export `OPFSDirWrap` and `OPFSFileWrap` to prevent potential breaking changes in the future.

**Comment by ElasticBottle** [comment]
Fair enough, thanks! Might try to send a reproducible demo in the future. Idk why I'm getting the error since I swear I'm lazily importing this from the client.

**Comment by hughfenghen** [comment]
👌，you can reopen this issue when needed.
